// <auto-generated />
using System;
using LaunchData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaunchData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaunchData.Models.Core", b =>
                {
                    b.Property<string>("CoreId")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "core");

                    b.Property<int?>("Flight")
                        .HasColumnType("int");

                    b.Property<bool?>("Gridfins")
                        .HasColumnType("bit");

                    b.Property<bool?>("LandingAttempt")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "landing_attempt");

                    b.Property<bool?>("LandingSuccess")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "landing_success");

                    b.Property<string>("LandingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "landing_type");

                    b.Property<string>("Landpad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaunchModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Legs")
                        .HasColumnType("bit");

                    b.Property<bool?>("Reused")
                        .HasColumnType("bit");

                    b.HasKey("CoreId");

                    b.HasIndex("LaunchModelId");

                    b.ToTable("Cores");
                });

            modelBuilder.Entity("LaunchData.Models.Failure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaunchModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LaunchModelId");

                    b.ToTable("Failures");
                });

            modelBuilder.Entity("LaunchData.Models.Fairings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Recovered")
                        .HasColumnType("bit");

                    b.Property<bool?>("RecoveryAttempt")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "recovery_attempt");

                    b.Property<bool?>("Reused")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Ships")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fairings");
                });

            modelBuilder.Entity("LaunchData.Models.Flickr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Original")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Small")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flickr");
                });

            modelBuilder.Entity("LaunchData.Models.Links", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlickrId")
                        .HasColumnType("int");

                    b.Property<int>("PatchId")
                        .HasColumnType("int");

                    b.Property<string>("Presskit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RedditId")
                        .HasColumnType("int");

                    b.Property<string>("Webcast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wikipedia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "youtube_id");

                    b.HasKey("Id");

                    b.HasIndex("FlickrId");

                    b.HasIndex("PatchId");

                    b.HasIndex("RedditId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("LaunchData.Models.Patch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Large")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Small")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patch");
                });

            modelBuilder.Entity("LaunchData.Models.Reddit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Campaign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Launch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recovery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reddit");
                });

            modelBuilder.Entity("LaunchModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "auto_update");

                    b.PrimitiveCollection<string>("Capsules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Crew")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "date_local");

                    b.Property<string>("DatePrecision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "date_precision");

                    b.Property<long>("DateUnix")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "date_unix");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "date_utc");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FairingsId")
                        .HasColumnType("int");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "flight_number");

                    b.Property<string>("LaunchLibraryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "launch_library_id");

                    b.Property<string>("Launchpad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "launchpad");

                    b.Property<int>("LinksId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Net")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Payloads")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rocket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Ships")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StaticFireDateUnix")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "static_fire_date_unix");

                    b.Property<DateTime?>("StaticFireDateUtc")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "static_fire_date_utc");

                    b.Property<bool?>("Success")
                        .HasColumnType("bit");

                    b.Property<bool>("Tbd")
                        .HasColumnType("bit");

                    b.Property<bool>("Upcoming")
                        .HasColumnType("bit");

                    b.Property<int?>("Window")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FairingsId");

                    b.HasIndex("LinksId");

                    b.ToTable("LaunchModels");
                });

            modelBuilder.Entity("LaunchData.Models.Core", b =>
                {
                    b.HasOne("LaunchModel", null)
                        .WithMany("Cores")
                        .HasForeignKey("LaunchModelId");
                });

            modelBuilder.Entity("LaunchData.Models.Failure", b =>
                {
                    b.HasOne("LaunchModel", null)
                        .WithMany("Failures")
                        .HasForeignKey("LaunchModelId");
                });

            modelBuilder.Entity("LaunchData.Models.Links", b =>
                {
                    b.HasOne("LaunchData.Models.Flickr", "Flickr")
                        .WithMany()
                        .HasForeignKey("FlickrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchData.Models.Patch", "Patch")
                        .WithMany()
                        .HasForeignKey("PatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchData.Models.Reddit", "Reddit")
                        .WithMany()
                        .HasForeignKey("RedditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flickr");

                    b.Navigation("Patch");

                    b.Navigation("Reddit");
                });

            modelBuilder.Entity("LaunchModel", b =>
                {
                    b.HasOne("LaunchData.Models.Fairings", "Fairings")
                        .WithMany()
                        .HasForeignKey("FairingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchData.Models.Links", "Links")
                        .WithMany()
                        .HasForeignKey("LinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fairings");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("LaunchModel", b =>
                {
                    b.Navigation("Cores");

                    b.Navigation("Failures");
                });
#pragma warning restore 612, 618
        }
    }
}
